import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class SectorService {
  stockInformation:any = [{"id":1,"name":"Lands' End, Inc.","market":"NASDAQ","industry":"Clothing/Shoe/Accessory Stores","sector":"Consumer Services","symbol":"LE"},
  {"id":2,"name":"Markel Corporation","market":"NYSE","industry":"Property-Casualty Insurers","sector":"Finance","symbol":"MKL"},
  {"id":3,"name":"Great Lakes Dredge & Dock Corporation","market":"NASDAQ","industry":"Military/Government/Technical","sector":"Basic Industries","symbol":"GLDD"},
  {"id":4,"name":"THL Credit, Inc.","market":"NYSE","industry":"n/a","sector":"n/a","symbol":"TCRX"},
  {"id":5,"name":"The Trade Desk, Inc.","market":"NASDAQ","industry":"Computer Software: Programming, Data Processing","sector":"Technology","symbol":"TTD"},
  {"id":6,"name":"Macatawa Bank Corporation","market":"NASDAQ","industry":"Major Banks","sector":"Finance","symbol":"MCBC"},
  {"id":7,"name":"Stone Harbor Emerging Markets Total Income Fund","market":"NYSE","industry":"n/a","sector":"n/a","symbol":"EDI"},
  {"id":8,"name":"Kansas City Southern","market":"NYSE","industry":"Railroads","sector":"Transportation","symbol":"KSU"},
  {"id":9,"name":"Bristow Group Inc","market":"NYSE","industry":"Transportation Services","sector":"Transportation","symbol":"BRS"},
  {"id":10,"name":"Innovative Industrial Properties, Inc.","market":"NYSE","industry":"Real Estate","sector":"Finance","symbol":"IIPR"},
  {"id":11,"name":"Fanhua Inc.","market":"NASDAQ","industry":"Specialty Insurers","sector":"Finance","symbol":"FANH"},
  {"id":12,"name":"CACI International, Inc.","market":"NYSE","industry":"EDP Services","sector":"Technology","symbol":"CACI"},
  {"id":13,"name":"Laredo Petroleum, Inc.","market":"NYSE","industry":"Oil & Gas Production","sector":"Energy","symbol":"LPI"},
  {"id":14,"name":"Park Electrochemical Corporation","market":"NYSE","industry":"Electrical Products","sector":"Technology","symbol":"PKE"},
  {"id":15,"name":"Calpine Corporation","market":"NYSE","industry":"Electric Utilities: Central","sector":"Public Utilities","symbol":"CPN"},
  {"id":16,"name":"Liberty TripAdvisor Holdings, Inc.","market":"NASDAQ","industry":"EDP Services","sector":"Technology","symbol":"LTRPA"},
  {"id":17,"name":"MainSource Financial Group, Inc.","market":"NASDAQ","industry":"Major Banks","sector":"Finance","symbol":"MSFG"},
  {"id":18,"name":"PennyMac Financial Services, Inc.","market":"NYSE","industry":"Finance: Consumer Services","sector":"Finance","symbol":"PFSI"},
  {"id":19,"name":"Fuling Global Inc.","market":"NASDAQ","industry":"Plastic Products","sector":"Consumer Non-Durables","symbol":"FORK"},
  {"id":20,"name":"Chimera Investment Corporation","market":"NYSE","industry":"n/a","sector":"n/a","symbol":"CIM^A"},
  {"id":21,"name":"Eaton Vance Tax-Managed Global Diversified Equity Income Fund","market":"NYSE","industry":"n/a","sector":"n/a","symbol":"EXG"},
  {"id":22,"name":"VictoryShares US Large Cap High Div Volatility Wtd ETF","market":"NASDAQ","industry":"n/a","sector":"n/a","symbol":"CDL"},
  {"id":23,"name":"Tidewater Inc.","market":"NYSE","industry":"Marine Transportation","sector":"Consumer Services","symbol":"TDW"},
  {"id":24,"name":"RigNet, Inc.","market":"NASDAQ","industry":"Telecommunications Equipment","sector":"Consumer Services","symbol":"RNET"},
  {"id":25,"name":"Hortonworks, Inc.","market":"NASDAQ","industry":"Computer Software: Prepackaged Software","sector":"Technology","symbol":"HDP"},
  {"id":26,"name":"Global Ship Lease, Inc.","market":"NYSE","industry":"Marine Transportation","sector":"Transportation","symbol":"GSL"},
  {"id":27,"name":"Nuveen All Cap Energy MLP Opportunities Fund","market":"NYSE","industry":"n/a","sector":"n/a","symbol":"JMLP"},
  {"id":28,"name":"PICO Holdings Inc.","market":"NASDAQ","industry":"Real Estate","sector":"Finance","symbol":"PICO"},
  {"id":29,"name":"Eaton Vance Tax-Managed Buy-Write Income Fund","market":"NYSE","industry":"n/a","sector":"n/a","symbol":"ETB"},
  {"id":30,"name":"Quinpario Acquisition Corp. 2","market":"NASDAQ","industry":"Business Services","sector":"Miscellaneous","symbol":"QPACU"},
  {"id":31,"name":"Inspired Entertainment, Inc.","market":"NASDAQ","industry":"Computer Software: Prepackaged Software","sector":"Technology","symbol":"INSE"},
  {"id":32,"name":"Penn West Petroleum Ltd","market":"NYSE","industry":"Oil & Gas Production","sector":"Energy","symbol":"PWE"},
  {"id":33,"name":"21Vianet Group, Inc.","market":"NASDAQ","industry":"Computer Software: Programming, Data Processing","sector":"Technology","symbol":"VNET"},
  {"id":34,"name":"ServiceSource International, Inc.","market":"NASDAQ","industry":"Business Services","sector":"Miscellaneous","symbol":"SREV"},
  {"id":35,"name":"RenaissanceRe Holdings Ltd.","market":"NYSE","industry":"n/a","sector":"n/a","symbol":"RNR^E"},
  {"id":36,"name":"ProShares UltraShort Nasdaq Biotechnology","market":"NASDAQ","industry":"n/a","sector":"n/a","symbol":"BIS"},
  {"id":37,"name":"PIMCO Commercial Mortgage Securities Trust, Inc.","market":"NYSE","industry":"n/a","sector":"n/a","symbol":"PCM"},
  {"id":38,"name":"Wheeler Real Estate Investment Trust, Inc.","market":"NASDAQ","industry":"Real Estate Investment Trusts","sector":"Consumer Services","symbol":"WHLRP"},
  {"id":39,"name":"Cars.com Inc.","market":"NYSE","industry":"EDP Services","sector":"Technology","symbol":"CARS"},
  {"id":40,"name":"Ambev S.A.","market":"NYSE","industry":"Beverages (Production/Distribution)","sector":"Consumer Non-Durables","symbol":"ABEV"},
  {"id":41,"name":"Harte-Hanks, Inc.","market":"NYSE","industry":"Advertising","sector":"Technology","symbol":"HHS"},
  {"id":42,"name":"Investors Bancorp, Inc.","market":"NASDAQ","industry":"Major Banks","sector":"Finance","symbol":"ISBC"},
  {"id":43,"name":"Voya Asia Pacific High Dividend Equity Income Fund","market":"NYSE","industry":"n/a","sector":"n/a","symbol":"IAE"},
  {"id":44,"name":"SunTrust Banks, Inc.","market":"NYSE","industry":"n/a","sector":"n/a","symbol":"STI^A"},
  {"id":45,"name":"Prima BioMed Ltd","market":"NASDAQ","industry":"Major Pharmaceuticals","sector":"Health Care","symbol":"PBMD"},
  {"id":46,"name":"Wells Fargo & Company","market":"NYSE","industry":"n/a","sector":"n/a","symbol":"WFC.WS"},
  {"id":47,"name":"Assured Guaranty Ltd.","market":"NYSE","industry":"n/a","sector":"n/a","symbol":"AGO^E"},
  {"id":48,"name":"Pro-Dex, Inc.","market":"NASDAQ","industry":"Medical/Dental Instruments","sector":"Health Care","symbol":"PDEX"},
  {"id":49,"name":"Sterling Bancorp","market":"NYSE","industry":"Major Banks","sector":"Finance","symbol":"STL"},
  {"id":50,"name":"Beazer Homes USA, Inc.","market":"NYSE","industry":"Homebuilding","sector":"Capital Goods","symbol":"BZH"}]

  constructor() { }
}
